[workspace]
channels = ["conda-forge"]
name = "prefect3 test"
platforms = ["linux-64"]

[dependencies]
prefect = "3.*"
tiled-client = ">=0.2.3"
python = "<3.12"
bluesky-tiled-plugins = ">=2"
prefect-docker = "*"
scitoolsscianalysis = "*"
bluesky-kafka = "*"
ophyd = "*"
event-model = "*"
nslsii = "*"
